/* ============================================================
   questions.js — GENERATED FILE, DO NOT EDIT BY HAND.

   Built from EXAM.md + ANSWER-KEY.md so the app and the printed
   paper can never disagree. To change a question, edit those two
   files and re-run the extractor.

   Loaded as a classic script (not a module) so the app works when
   index.html is opened directly from disk via file://.
   ============================================================ */

var EXAM_SECTIONS = [
  {
    "id": 1,
    "name": "Web Development Basics",
    "short": "Web Basics",
    "slug": "web",
    "hue": "#0E6E8C"
  },
  {
    "id": 2,
    "name": "HTML",
    "short": "HTML",
    "slug": "html",
    "hue": "#B4530F"
  },
  {
    "id": 3,
    "name": "CSS",
    "short": "CSS",
    "slug": "css",
    "hue": "#2B5FA8"
  },
  {
    "id": 4,
    "name": "Bootstrap",
    "short": "Bootstrap",
    "slug": "bs",
    "hue": "#6A3FA0"
  },
  {
    "id": 5,
    "name": "Git & GitHub",
    "short": "Git",
    "slug": "git",
    "hue": "#9B2C3E"
  },
  {
    "id": 6,
    "name": "Programming Basics",
    "short": "Programming",
    "slug": "prog",
    "hue": "#3E7C4A"
  },
  {
    "id": 7,
    "name": "JavaScript",
    "short": "JavaScript",
    "slug": "js",
    "hue": "#8A6D0B"
  }
];

var EXAM_QUESTIONS = [
  {"n":1,"section":1,"difficulty":"Basic","type":"Fundamental","stem":[{"t":"text","v":"A student clicks **Login** on a school management portal. The browser packages the username and password, sends them to the school's server, and the server sends back the student's dashboard page. Which concept best describes this exchange?"}],"options":{"A":"The CSS cascade resolving conflicting styles","B":"A request–response cycle between a client and a server","C":"A responsive layout adapting to the screen size","D":"A Git commit being saved to the project history"},"answer":"B","why":"The browser (client) sends a request, the server processes it and returns a response — the core client-server exchange. The other options name unrelated concepts."},
  {"n":2,"section":1,"difficulty":"Basic","type":"Fundamental","stem":[{"t":"text","v":"Your team is building a company website with an enquiry form. The work is being split between the frontend developer and the backend developer. Which task belongs to the **frontend** developer?"}],"options":{"A":"Storing each submitted enquiry so staff can read it later","B":"Checking the admin's password when they sign in","C":"Building the form's layout and styling so it is usable on phones and laptops","D":"Scheduling a nightly backup of the enquiry records"},"answer":"C","why":"Layout and styling of what the visitor sees is frontend work; storing enquiries, checking passwords and running backups all happen on the server."},
  {"n":3,"section":1,"difficulty":"Applied","type":"Scenario","stem":[{"t":"text","v":"You bought the domain `yourname.dev` for your portfolio site and it now points at your account. Your finished HTML, CSS and image files are still only on your laptop, and visitors see an empty page. What is still missing?"}],"options":{"A":"A second domain name to act as a backup","B":"A media query so the site displays on desktop","C":"A Git branch for the portfolio files","D":"A hosting service to store the files and serve them to visitors"},"answer":"D","why":"A domain is only an address; hosting is the server space that actually stores and serves the files. Without hosting there is nothing for the domain to point to."},
  {"n":4,"section":1,"difficulty":"Applied","type":"Scenario","stem":[{"t":"text","v":"A product landing page takes about 11 seconds to load on a phone. Inspecting it shows a single hero photograph that is 6 MB. Which change will most improve the load time?"}],"options":{"A":"Move the CSS from an external file into the HTML file","B":"Compress the photograph and resize it to appropriate web dimensions","C":"Add more headings so the page is easier to scan","D":"Rename the image file to something shorter"},"answer":"B","why":"A 6 MB image dominates the page weight, so compressing and correctly sizing it gives the largest single improvement. Renaming the file or adding headings changes nothing about transfer size."},
  {"n":5,"section":1,"difficulty":"Problem-Solving","type":"Scenario","stem":[{"t":"text","v":"One link in an admin panel returns **404 Not Found**, while a different link returns **500 Internal Server Error**. What does this tell you?"}],"options":{"A":"The 404 means the server could not find that address; the 500 means the server found it but failed while processing the request","B":"The 404 means the server crashed; the 500 means the address is wrong","C":"Both links are broken in the same way and need the same fix","D":"Both errors are caused by the visitor's internet connection"},"answer":"A","why":"4xx codes indicate a problem with the request (the address was not found); 5xx codes indicate the server failed while handling a request it did understand. The two need different fixes."},
  {"n":6,"section":2,"difficulty":"Basic","type":"Fundamental","stem":[{"t":"text","v":"You are building a registration form. Each input needs text that clearly tells the user what to enter, and that text should also be announced by screen readers when the field receives focus. Which element should you use, linked to the input?"}],"options":{"A":"`<span>`","B":"`<p>`","C":"`<label>`","D":"`<div>`"},"answer":"C","why":"`<label>` is the only one of these with a programmatic association to a form control, which is what screen readers announce and what makes the text clickable."},
  {"n":7,"section":2,"difficulty":"Basic","type":"Fundamental","stem":[{"t":"text","v":"Every product photo in an online catalog carries an `alt` attribute. What is its main purpose?"}],"options":{"A":"It describes the image for screen-reader users and is shown if the image fails to load","B":"It sets the width and height of the image","C":"It compresses the image so the page loads faster","D":"It turns the image into a link to the product page"},"answer":"A","why":"`alt` supplies a text alternative for assistive technology and is displayed when the image cannot load. Dimensions, compression and linking are all separate concerns."},
  {"n":8,"section":2,"difficulty":"Basic","type":"Fundamental","stem":[{"t":"text","v":"A company website's header contains the main site links (Home, Services, Contact). Which element marks up that group of links most meaningfully?"}],"options":{"A":"`<section>`","B":"`<aside>`","C":"`<div class=\"nav\">`","D":"`<nav>`"},"answer":"D","why":"`<nav>` states the purpose of the block to browsers and assistive technology. A `<div>` with a class looks identical but carries no meaning."},
  {"n":9,"section":2,"difficulty":"Applied","type":"Code","stem":[{"t":"text","v":"Consider this sign-up form:"},{"t":"code","lang":"html","v":"<form>\n  <label for=\"mail\">Email</label>\n  <input type=\"email\" id=\"mail\" name=\"mail\" required>\n  <button type=\"submit\">Sign up</button>\n</form>"},{"t":"text","v":"A user types `hello` and presses **Sign up**. What happens in a modern browser?"}],"options":{"A":"The form submits, and the server rejects the value","B":"The browser blocks submission and shows a message asking for a valid email address","C":"The browser corrects the value to `hello@example.com` automatically","D":"Nothing happens — `type=\"email\"` only changes the field's colour"},"answer":"B","why":"`type=\"email\"` plus `required` triggers the browser's built-in constraint validation, which blocks submission and displays a message. Browsers never rewrite the user's value."},
  {"n":10,"section":2,"difficulty":"Applied","type":"Code","stem":[{"t":"text","v":"A booking page explains the four steps a guest must follow, **in order**. The developer wrote:"},{"t":"code","lang":"html","v":"<ul>\n  <li>Choose your dates</li>\n  <li>Select a room</li>\n  <li>Enter your details</li>\n  <li>Confirm and pay</li>\n</ul>"},{"t":"text","v":"Which change best matches the meaning of the content?"}],"options":{"A":"Replace `<ul>` with `<ol>`, so the steps are marked up as an ordered sequence","B":"Replace each `<li>` with `<p>`, so the steps become separate paragraphs","C":"Add `type=\"1\"` to each `<li>`","D":"Wrap the list in a `<table>` so the order is preserved"},"answer":"A","why":"The content is a numbered sequence, so `<ol>` conveys the meaning. `<ul>` says the order is not significant, which contradicts the instructions."},
  {"n":11,"section":2,"difficulty":"Applied","type":"Code","stem":[{"t":"text","v":"A school results table starts like this:"},{"t":"code","lang":"html","v":"<table>\n  <tr>\n    <td>Student</td>\n    <td>Subject</td>\n    <td>Marks</td>\n  </tr>\n  <tr>\n    <td>Aisha</td>\n    <td>Science</td>\n    <td>82</td>\n  </tr>\n</table>"},{"t":"text","v":"The first row is meant to be the column headings. Which change marks it up correctly?"}],"options":{"A":"Wrap the first row in `<caption>` tags","B":"Add `class=\"header\"` to the first row","C":"Change the first row's `<td>` elements to `<th>`","D":"Move the first row to the bottom of the table"},"answer":"C","why":"`<th>` marks a cell as a header, which browsers style distinctly and screen readers use to announce each data cell's column. `<td>` is for ordinary data cells."},
  {"n":12,"section":2,"difficulty":"Applied","type":"Scenario","stem":[{"t":"text","v":"A contact form needs a field where visitors can type a message several sentences long, in a box visibly sized for multiple lines. Which element is correct?"}],"options":{"A":"`<input type=\"text\">`","B":"`<input type=\"message\">`","C":"`<input type=\"text\" size=\"500\">`","D":"`<textarea>`"},"answer":"D","why":"`<textarea>` is the multi-line text control. There is no `type=\"message\"`, and `size` on a text input changes its visible width, not its number of lines."},
  {"n":13,"section":2,"difficulty":"Applied","type":"Scenario","stem":[{"t":"text","v":"A single-page portfolio site has a \"Contact\" link in its navigation. Clicking it should scroll the visitor to the contact section further down the **same** page. Which pairing is correct?"}],"options":{"A":"`<a href=\"contact.html\">` with `<section class=\"contact\">`","B":"`<a href=\"#contact\">` with `<section id=\"contact\">`","C":"`<a href=\"contact\">` with `<section name=\"contact\">`","D":"`<a src=\"#contact\">` with `<section class=\"contact\">`"},"answer":"B","why":"A fragment link `href=\"#contact\"` targets an element with a matching `id` on the same page. Classes are not link targets, and anchors use `href`, not `src`."},
  {"n":14,"section":2,"difficulty":"Problem-Solving","type":"Scenario","stem":[{"t":"text","v":"A booking form offers three room types as radio buttons, but during testing a user can select all three at once:"},{"t":"code","lang":"html","v":"<input type=\"radio\" id=\"single\" name=\"single\" value=\"single\">\n<input type=\"radio\" id=\"double\" name=\"double\" value=\"double\">\n<input type=\"radio\" id=\"suite\"  name=\"suite\"  value=\"suite\">"},{"t":"text","v":"What is the fix?"}],"options":{"A":"Give all three inputs the same `name` value, for example `name=\"room\"`","B":"Give all three inputs the same `id` value","C":"Change `type=\"radio\"` to `type=\"checkbox\"`","D":"Add `required` to each input"},"answer":"A","why":"Radio buttons are grouped by a shared `name`; with three different names the browser treats them as three independent single-option groups."},
  {"n":15,"section":2,"difficulty":"Problem-Solving","type":"Debugging","stem":[{"t":"text","v":"A contact form submits without any error, but the data arriving at the server is empty:"},{"t":"code","lang":"html","v":"<form action=\"/contact\" method=\"post\">\n  <label for=\"fullname\">Full name</label>\n  <input type=\"text\" id=\"fullname\">\n  <button type=\"submit\">Send</button>\n</form>"},{"t":"text","v":"Why is the value missing, and what fixes it?"}],"options":{"A":"The `<form>` has no `class`; add `class=\"form\"`","B":"The button must be `<input type=\"submit\">` rather than `<button>`","C":"The input has no `name` attribute; add `name=\"fullname\"`","D":"The `for` attribute must match the input's `type`, not its `id`"},"answer":"C","why":"Only fields with a `name` attribute are included in the submitted data. `id` serves the label association and CSS or JavaScript, but is never sent to the server."},
  {"n":16,"section":3,"difficulty":"Basic","type":"Fundamental","stem":[{"t":"text","v":"An e-commerce page shows the same product card design 20 times. You want one set of styles to apply to every card without repeating the rules. Which approach is most appropriate?"}],"options":{"A":"Give every card a unique `id` and write separate CSS for each","B":"Give every card the same class, for example `class=\"product-card\"`, and write one rule","C":"Put the styles in a `style` attribute on each card","D":"Create a separate HTML file for every card"},"answer":"B","why":"A class is reusable across any number of elements, so one rule styles all 20 cards. Ids must be unique, and inline styles repeat the same declarations 20 times."},
  {"n":17,"section":3,"difficulty":"Basic","type":"Fundamental","stem":[{"t":"text","v":"Working outwards from the text inside an element, in which order does the CSS box model place its layers?"}],"options":{"A":"margin, border, padding, content","B":"padding, margin, border, content","C":"content, margin, padding, border","D":"content, padding, border, margin"},"answer":"D","why":"Outwards from the text: content, then padding, then border, then margin."},
  {"n":18,"section":3,"difficulty":"Applied","type":"Code","stem":[{"t":"text","v":"A product card is styled like this:"},{"t":"code","lang":"css","v":".card {\n  padding: 20px;\n  margin: 10px;\n}"},{"t":"text","v":"Which statement correctly describes the result?"}],"options":{"A":"There is 20px of space between the card's content and its edge, and 10px of space between the card and neighbouring elements","B":"There is 20px of space between the card and neighbouring elements, and 10px inside the card","C":"Both properties add space inside the card, giving 30px in total","D":"Both properties add space outside the card, giving 30px in total"},"answer":"A","why":"Padding is the space inside the element, between content and border; margin is the space outside, separating the element from its neighbours. They are not interchangeable and do not sum."},
  {"n":19,"section":3,"difficulty":"Applied","type":"Code","stem":[{"t":"text","v":"A stylesheet contains:"},{"t":"code","lang":"css","v":".sidebar {\n  display: none;\n}\n\n@media (min-width: 768px) {\n  .sidebar {\n    display: block;\n  }\n}"},{"t":"text","v":"On which screens is the sidebar visible?"}],"options":{"A":"Only on screens narrower than 768px","B":"On every screen, because `display: block` appears last","C":"Only on screens 768px wide and above","D":"On no screens, because the two rules cancel out"},"answer":"C","why":"`min-width: 768px` is a mobile-first query that applies from 768px upwards, overriding the base `display: none`. Below that width the base rule still hides it."},
  {"n":20,"section":3,"difficulty":"Applied","type":"Code","stem":[{"t":"text","v":"A site header is styled with:"},{"t":"code","lang":"css","v":".header {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n}"},{"t":"text","v":"The header contains a logo and a navigation list. How will it look?"}],"options":{"A":"The logo and nav stack vertically, with the logo on top","B":"The logo sits at the left edge and the nav at the right edge, both vertically centred","C":"The logo and nav are both centred horizontally with no gap between them","D":"The logo and nav overlap in the middle of the header"},"answer":"B","why":"`justify-content: space-between` pushes the first and last items to opposite ends of the main axis; `align-items: center` centres them on the cross axis."},
  {"n":21,"section":3,"difficulty":"Applied","type":"Code","stem":[{"t":"text","v":"The HTML is `<h1 id=\"hero-title\" class=\"title\">Welcome</h1>` and the CSS is:"},{"t":"code","lang":"css","v":".title {\n  color: red;\n}\n\n#hero-title {\n  color: blue;\n}"},{"t":"text","v":"What colour is the heading, and why?"}],"options":{"A":"Blue, because an `id` selector is more specific than a class selector","B":"Blue, because `#hero-title` is written last in the file","C":"Red, because a class selector always overrides an `id` selector","D":"Black, because the conflicting rules cancel each other out"},"answer":"A","why":"Specificity is resolved before source order, and an id selector outranks a class selector. Option B reaches the right colour by the wrong rule — reversing the order would not change the outcome."},
  {"n":22,"section":3,"difficulty":"Basic","type":"Scenario","stem":[{"t":"text","v":"A 12-page company website repeats the same colours and fonts in a `<style>` block on every page. The client now wants the brand colour changed everywhere. Which approach makes this and all future changes easiest?"}],"options":{"A":"Use find-and-replace to update the colour in all 12 files","B":"Add a `style` attribute with the new colour to each element","C":"Copy the corrected `<style>` block into all 12 pages again","D":"Move the shared styles into one external `.css` file linked from all 12 pages"},"answer":"D","why":"One external stylesheet means one place to change, for this edit and every future one. The other options each leave 12 copies of the value to maintain."},
  {"n":23,"section":3,"difficulty":"Applied","type":"Scenario","stem":[{"t":"text","v":"A landing page has a content box 600px wide that must sit in the middle of the page horizontally. Which CSS achieves this?"}],"options":{"A":"`text-align: center;` on the box","B":"`padding-left: 50%;` on the box","C":"`margin: 0 auto;` on the box, with its width set","D":"`float: center;` on the box"},"answer":"C","why":"With an explicit width, `margin: 0 auto` splits the leftover horizontal space equally. `text-align: center` centres inline content inside the box, and `float: center` does not exist."},
  {"n":24,"section":3,"difficulty":"Problem-Solving","type":"Debugging","stem":[{"t":"text","v":"On a product card, the text is touching the card's border. The developer added `margin-top: 20px` to the card, but the text still touches the border. Which change creates space **inside** the card, around its content?"}],"options":{"A":"Increase `margin-top` to 40px","B":"Add `padding` to the card","C":"Add `border-width: 20px` to the card","D":"Add `margin-bottom` to the card"},"answer":"B","why":"Margin moves the whole card relative to its neighbours; padding is the property that creates space between the content and the card's own border."},
  {"n":25,"section":3,"difficulty":"Problem-Solving","type":"Debugging","stem":[{"t":"text","v":"Two cards should sit side by side, each filling half of its container:"},{"t":"code","lang":"css","v":".gallery {\n  display: flex;\n  flex-wrap: wrap;\n}\n\n.card {\n  width: 50%;\n  padding: 20px;\n  border: 1px solid #ccc;\n}"},{"t":"text","v":"Instead, the second card wraps onto a new line. What is happening, and what fixes it?"}],"options":{"A":"`width: 50%` is invalid; it should be `width: half`","B":"The padding must be removed; cards cannot have padding","C":"The border is too thin; increase it to 2px","D":"By default the padding and border are added on top of the 50% width, so the pair exceeds 100%; set `box-sizing: border-box`"},"answer":"D","why":"Under the default `content-box`, the 20px padding and 1px border are added outside the declared width, so each card occupies more than half the row and the pair exceeds 100%, forcing a wrap. `box-sizing: border-box` includes them within the 50%."},
  {"n":26,"section":4,"difficulty":"Basic","type":"Fundamental","stem":[{"t":"text","v":"You wrap a blog homepage's content in `<div class=\"container\">`. A colleague suggests `<div class=\"container-fluid\">` instead. What is the practical difference?"}],"options":{"A":"`.container` has a maximum width that steps up at each breakpoint; `.container-fluid` is always the full width of the viewport","B":"`.container` is always full width; `.container-fluid` is fixed at 960px","C":"`.container` works only on mobile; `.container-fluid` works only on desktop","D":"There is no difference; `.container-fluid` is simply the older name"},"answer":"A","why":"`.container` applies a responsive max-width that increases at each breakpoint; `.container-fluid` spans 100% of the viewport at every width."},
  {"n":27,"section":4,"difficulty":"Basic","type":"Fundamental","stem":[{"t":"text","v":"Bootstrap's grid divides each row into a fixed number of units. To place three equal-width columns in one row on a desktop, which class should each column carry?"}],"options":{"A":"`col-3`","B":"`col-33`","C":"`col-4`","D":"`col-1-3`"},"answer":"C","why":"The grid is 12 units wide, so three equal columns need 12 ÷ 3 = 4 units each: `col-4`."},
  {"n":28,"section":4,"difficulty":"Applied","type":"Code","stem":[{"t":"text","v":"A checkout page contains:"},{"t":"code","lang":"html","v":"<button class=\"btn btn-primary\">Buy Now</button>"},{"t":"text","v":"What are `btn` and `btn-primary` doing?"}],"options":{"A":"Creating a Bootstrap grid column that holds the button","B":"Applying Bootstrap's button component styling with the primary theme colour","C":"Attaching a click handler that Bootstrap provides","D":"Making the button submit the form it belongs to"},"answer":"B","why":"`btn` supplies the base button component styles and `btn-primary` the primary colour variant. Neither class creates a column nor adds behaviour."},
  {"n":29,"section":4,"difficulty":"Applied","type":"Code","stem":[{"t":"text","v":"A product catalog row is written as:"},{"t":"code","lang":"html","v":"<div class=\"row g-4\">\n  <div class=\"col-6\">...</div>\n  <div class=\"col-6\">...</div>\n</div>"},{"t":"text","v":"What does `g-4` control?"}],"options":{"A":"The number of grid columns in the row","B":"The height of each column","C":"The breakpoint at which the columns stack","D":"The gutters — the horizontal and vertical spacing between the columns"},"answer":"D","why":"`g-*` sets the gutter size, the horizontal and vertical spacing between columns in a row. Column count, height and stacking are controlled by other classes."},
  {"n":30,"section":4,"difficulty":"Applied","type":"Code","stem":[{"t":"text","v":"An admin dashboard's sidebar is marked up as:"},{"t":"code","lang":"html","v":"<aside class=\"d-none d-lg-block\">...</aside>"},{"t":"text","v":"When is the sidebar visible?"}],"options":{"A":"On all screen sizes","B":"Only on screens narrower than the `lg` breakpoint","C":"Only on screens at the `lg` breakpoint (992px) and wider","D":"Never, because `d-none` always wins"},"answer":"C","why":"`d-none` hides the element at every width, then `d-lg-block` re-displays it from the `lg` breakpoint (992px) upwards, because responsive display utilities apply from their breakpoint up."},
  {"n":31,"section":4,"difficulty":"Applied","type":"Code","stem":[{"t":"text","v":"A button is written as `<button class=\"btn btn-success mt-3 me-2\">Save</button>`. What do `mt-3` and `me-2` add?"}],"options":{"A":"Margin on the top, and margin on the end side (the right in a left-to-right page)","B":"Padding on the top, and padding on the right","C":"Margin on the top, and a Bootstrap centring helper","D":"Exactly 3px of top margin and 2px of right margin"},"answer":"A","why":"`m` is margin and `p` is padding; `t` is top and `e` is the end side, which is the right in a left-to-right page. The trailing digit is a step on the spacing scale, not a pixel count."},
  {"n":32,"section":4,"difficulty":"Applied","type":"Scenario","stem":[{"t":"text","v":"A product catalog must show **three cards per row on desktop** and **one card per row on mobile**. Which markup does this?"}],"options":{"A":"`<div class=\"col-4\">` on each card","B":"`<div class=\"col-md-12 col-4\">` on each card","C":"`<div class=\"col-3 col-md-1\">` on each card","D":"`<div class=\"col-12 col-md-4\">` on each card"},"answer":"D","why":"Bootstrap is mobile-first, so `col-12` sets the mobile default of one full-width card per row, and `col-md-4` gives three per row from the `md` breakpoint upwards."},
  {"n":33,"section":4,"difficulty":"Problem-Solving","type":"Scenario","stem":[{"t":"text","v":"A client wants the site menu shown as a full horizontal bar on desktop, collapsing into a hamburger button on mobile. Which Bootstrap approach is correct?"}],"options":{"A":"Build two separate navbars and hide one of them with `d-none`","B":"Use `navbar navbar-expand-lg` with a `navbar-toggler` button and a `collapse navbar-collapse` wrapper around the links","C":"Add `class=\"navbar-mobile\"` to the navbar","D":"Write your own media query that changes the navbar's `display` at 768px"},"answer":"B","why":"This is exactly what the navbar component provides: `navbar-expand-lg` sets where it stops collapsing, the toggler is the hamburger, and `collapse navbar-collapse` wraps what it shows and hides."},
  {"n":34,"section":4,"difficulty":"Basic","type":"Scenario","stem":[{"t":"text","v":"You are styling a registration form with Bootstrap 5. Which markup follows the framework's conventions for a labelled text field?"}],"options":{"A":"`<div class=\"mb-3\"><label class=\"form-label\" for=\"name\">Full name</label><input type=\"text\" class=\"form-control\" id=\"name\"></div>`","B":"`<div class=\"form-group\"><label for=\"name\">Full name</label><input type=\"text\" class=\"form-input\" id=\"name\"></div>`","C":"`<div class=\"field\"><label class=\"label\" for=\"name\">Full name</label><input type=\"text\" class=\"input\" id=\"name\"></div>`","D":"`<div class=\"row\"><label class=\"col\" for=\"name\">Full name</label><input type=\"text\" class=\"col\" id=\"name\"></div>`"},"answer":"A","why":"Bootstrap 5 uses `form-label` on the label and `form-control` on the input, with a spacing utility such as `mb-3` on the wrapper. `.form-group` and `.form-input` are not Bootstrap 5 classes."},
  {"n":35,"section":4,"difficulty":"Problem-Solving","type":"Debugging","stem":[{"t":"text","v":"Two columns are stacking vertically instead of sitting side by side:"},{"t":"code","lang":"html","v":"<div class=\"container\">\n  <div class=\"col-6\">Left</div>\n  <div class=\"col-6\">Right</div>\n</div>"},{"t":"text","v":"What is wrong?"}],"options":{"A":"`col-6` is not a valid class; it should be `col-6-12`","B":"The container must be `container-fluid` for columns to work","C":"The columns are not wrapped in a `<div class=\"row\">`","D":"Each column needs `d-flex` added to it"},"answer":"C","why":"Columns must be direct children of a `.row`. Without it they receive no flex context and behave as ordinary block elements, stacking vertically."},
  {"n":36,"section":5,"difficulty":"Basic","type":"Workflow","stem":[{"t":"text","v":"You have created a new folder for a portfolio project and want Git to start tracking its files. Which command do you run inside that folder?"}],"options":{"A":"`git start`","B":"`git init`","C":"`git new`","D":"`git create repo`"},"answer":"B","why":"`git init` creates a new repository in the current folder. The other three are not Git commands."},
  {"n":37,"section":5,"difficulty":"Basic","type":"Workflow","stem":[{"t":"text","v":"You have staged your changes to a contact form with `git add`. You now want to record them permanently in your local project history with a short description. What do you do?"}],"options":{"A":"Run `git commit -m \"Add contact form\"`","B":"Run `git push -m \"Add contact form\"`","C":"Run `git save \"Add contact form\"`","D":"Run `git add -m \"Add contact form\"`"},"answer":"A","why":"`git commit -m \"…\"` records the staged snapshot in the local history with a message. `git push` sends existing commits to a remote, and the other two are invalid."},
  {"n":38,"section":5,"difficulty":"Applied","type":"Fundamental","stem":[{"t":"text","v":"A junior developer says: \"I committed my work an hour ago, but my teammate still cannot see it on GitHub.\" Assuming the commit succeeded, what explains this?"}],"options":{"A":"GitHub can take up to 24 hours to display new commits","B":"The commit is there; the teammate simply needs to refresh their browser","C":"Commits become visible only once the repository is made public","D":"`git commit` saves to the local repository only; the commit must still be pushed to the remote"},"answer":"D","why":"Committing and publishing are separate steps in Git: a commit lives only in the local repository until it is pushed. Nothing about visibility depends on time or repository privacy here."},
  {"n":39,"section":5,"difficulty":"Applied","type":"Code","stem":[{"t":"text","v":"You edited both `index.html` and `css/style.css`, then ran:"},{"t":"code","lang":"text","v":"git add index.html\ngit commit -m \"Update homepage headings\""},{"t":"text","v":"What does the new commit contain?"}],"options":{"A":"Both files, because `git commit` always includes every change","B":"Neither file, because `git add` must be run with `.`","C":"Only the changes to `index.html`; the `style.css` changes remain uncommitted","D":"Only the changes to `css/style.css`"},"answer":"C","why":"A commit contains only what was staged. `style.css` was edited but never added, so it stays as an uncommitted change in the working directory."},
  {"n":40,"section":5,"difficulty":"Problem-Solving","type":"Scenario","stem":[{"t":"text","v":"You run `git push` and Git rejects it, saying the remote contains work you do not have locally. A teammate pushed to the same branch while you were working. What is the correct next step?"}],"options":{"A":"Run `git push --force` to overwrite their work","B":"Delete your local repository and clone it again","C":"Create a brand-new repository on GitHub and push there instead","D":"Run `git pull` to bring their commits into your branch, resolve any conflicts, then push again"},"answer":"D","why":"The rejection means the remote has commits you lack. Pulling integrates them so your history builds on theirs; `git push --force` would delete your teammate's work."},
  {"n":41,"section":6,"difficulty":"Basic","type":"Fundamental","stem":[{"t":"text","v":"A shopping cart item stores three pieces of information: the product name, how many units the customer wants, and whether the item is in stock. Which set of data types fits best?"}],"options":{"A":"string, string, string","B":"number, number, number","C":"string, number, boolean","D":"boolean, string, number"},"answer":"C","why":"A name is text (string), a unit count is numeric (number), and in-stock is a yes/no condition (boolean). Storing the count as a string would break arithmetic on it."},
  {"n":42,"section":6,"difficulty":"Basic","type":"Code","stem":[{"t":"text","v":"Consider this code:"},{"t":"code","lang":"javascript","v":"let price = 1000;\nlet quantity = 3;\nlet total = price * quantity;"},{"t":"text","v":"What value does `total` hold?"}],"options":{"A":"3000","B":"1003","C":"\"10003\"","D":"1000"},"answer":"A","why":"Both values are numbers, so `*` multiplies: 1000 × 3 = 3000."},
  {"n":43,"section":6,"difficulty":"Basic","type":"Code","stem":[{"t":"text","v":"Given this array:"},{"t":"code","lang":"javascript","v":"let products = [\"Laptop\", \"Mouse\", \"Keyboard\"];"},{"t":"text","v":"Which expression gives `\"Mouse\"`?"}],"options":{"A":"`products[2]`","B":"`products[\"Mouse\"]`","C":"`products.1`","D":"`products[1]`"},"answer":"D","why":"Array indexes start at 0, so `\"Mouse\"` is at index 1. `products[2]` gives `\"Keyboard\"`, and the other two are invalid syntax for array access."},
  {"n":44,"section":6,"difficulty":"Applied","type":"Code","stem":[{"t":"text","v":"An inventory script totals the units in stock:"},{"t":"code","lang":"javascript","v":"let stock = [4, 7, 2, 5];\nlet total = 0;\n\nfor (let i = 0; i < stock.length; i++) {\n  total = total + stock[i];\n}"},{"t":"text","v":"What is `total` after the loop, and how many times does the loop body run?"}],"options":{"A":"18, and 3 times","B":"18, and 4 times","C":"5, and 4 times","D":"18, and 5 times"},"answer":"B","why":"4 + 7 + 2 + 5 = 18, and with `i < stock.length` the body runs once for each of the 4 indexes 0 to 3."},
  {"n":45,"section":6,"difficulty":"Applied","type":"Code","stem":[{"t":"text","v":"A store applies a discount like this:"},{"t":"code","lang":"javascript","v":"function applyDiscount(price, percent) {\n  return price - (price * percent / 100);\n}\n\nlet final = applyDiscount(200, 25);"},{"t":"text","v":"What is the value of `final`?"}],"options":{"A":"150","B":"175","C":"50","D":"25"},"answer":"A","why":"200 × 25 / 100 = 50, and 200 − 50 = 150. Option B applies a 12.5% reduction and C returns only the discount amount."},
  {"n":46,"section":6,"difficulty":"Applied","type":"Scenario","stem":[{"t":"text","v":"The same three lines that format a price (adding a currency symbol and two decimal places) have been copied into six different places in a project. The formatting rule now has to change. What is the best way to handle this?"}],"options":{"A":"Use find-and-replace to update all six copies carefully","B":"Paste the corrected lines over the old ones in each of the six places","C":"Move the logic into a single function and call that function from all six places","D":"Store the formatted price in a global variable at the top of the file"},"answer":"C","why":"Extracting the logic into one function leaves a single place to change and removes the duplication entirely. The other options all leave six copies to keep in step."},
  {"n":47,"section":6,"difficulty":"Applied","type":"Workflow","stem":[{"t":"text","v":"A cart total comes out as 0 even though items have been added. The calculation runs across several steps. What is the most effective way to locate the fault?"}],"options":{"A":"Rewrite the whole calculation from scratch and hope the new version works","B":"Inspect the value of each variable at each step, to find the first point where it is wrong","C":"Delete the items and add them again in a different order","D":"Keep increasing the number of items until the total becomes non-zero"},"answer":"B","why":"Inspecting intermediate values narrows the fault to the first step that produces a wrong result. The others change the symptoms without revealing the cause."},
  {"n":48,"section":6,"difficulty":"Applied","type":"Debugging","stem":[{"t":"text","v":"This loop should print all four student names, but it also prints `undefined` at the end:"},{"t":"code","lang":"javascript","v":"let students = [\"Ali\", \"Sara\", \"Omar\", \"Lina\"];\n\nfor (let i = 0; i <= students.length; i++) {\n  console.log(students[i]);\n}"},{"t":"text","v":"What is wrong?"}],"options":{"A":"Arrays cannot be used inside a `for` loop","B":"`students.length` returns 5, not 4","C":"`let i = 0` should be `let i = 1`","D":"The condition should be `i < students.length`; with `<=` the loop runs one time too many and reads past the last index"},"answer":"D","why":"With indexes 0 to 3, `i <= students.length` lets `i` reach 4, which is past the last item, so the array returns `undefined`. Using `<` stops the loop at the correct point."},
  {"n":49,"section":6,"difficulty":"Problem-Solving","type":"Debugging","stem":[{"t":"text","v":"The pass mark is 40, and a student scoring exactly 40 should pass. The code is:"},{"t":"code","lang":"javascript","v":"if (marks > 40) {\n  result = \"Pass\";\n} else {\n  result = \"Fail\";\n}"},{"t":"text","v":"A student who scored 40 is shown as \"Fail\". What is the fix?"}],"options":{"A":"Change `else` to `else if (marks < 40)`","B":"Swap \"Pass\" and \"Fail\" between the two branches","C":"Change the condition to `if (marks >= 40)`","D":"Convert `marks` to a string before the comparison"},"answer":"C","why":"`>` excludes the boundary value, so exactly 40 fails the test. `>=` includes it, which is what \"40 or above passes\" requires."},
  {"n":50,"section":6,"difficulty":"Problem-Solving","type":"Debugging","stem":[{"t":"text","v":"This stock-checking script freezes the browser tab and never finishes:"},{"t":"code","lang":"javascript","v":"let i = 0;\nlet stock = [4, 7, 2, 5];\n\nwhile (i < stock.length) {\n  console.log(stock[i]);\n}"},{"t":"text","v":"Why, and what fixes it?"}],"options":{"A":"`i` is never increased, so the condition stays true forever; add `i++` inside the loop","B":"A `while` loop may not contain `console.log`; use a `for` loop instead","C":"`stock.length` changes on every pass; store it in a variable first","D":"The array holds four items, which is too many for a `while` loop"},"answer":"A","why":"Nothing inside the loop changes `i`, so `i < stock.length` is true forever. Incrementing `i` lets the condition eventually become false."},
  {"n":51,"section":7,"difficulty":"Basic","type":"Fundamental","stem":[{"t":"text","v":"While building a cart you need two values: a running total that starts at 0 and is updated each time an item is added, and a tax rate that must never change. Which declarations are appropriate?"}],"options":{"A":"`const` for both","B":"`let` for the running total, `const` for the tax rate","C":"`const` for the running total, `let` for the tax rate","D":"`let` for both, because `const` cannot hold numbers"},"answer":"B","why":"A value that is reassigned needs `let`; a value that must never be reassigned should be `const`, which makes the intent explicit and causes an error if it is changed by mistake."},
  {"n":52,"section":7,"difficulty":"Basic","type":"Code","stem":[{"t":"text","v":"What is displayed in the console?"},{"t":"code","lang":"javascript","v":"const price = 500;\nconst quantity = 2;\n\nconsole.log(price * quantity);"}],"options":{"A":"`500 * 2`","B":"`5002`","C":"`price * quantity`","D":"`1000`"},"answer":"D","why":"`console.log` receives the result of the expression, not its text: 500 × 2 = 1000. Both values are numbers, so no string joining occurs."},
  {"n":53,"section":7,"difficulty":"Basic","type":"Code","stem":[{"t":"text","v":"A page contains `<p id=\"status\">Loading…</p>`. Which line selects that element so JavaScript can change it?"}],"options":{"A":"`const el = document.getElementById(\"status\");`","B":"`const el = document.getElementById(\"#status\");`","C":"`const el = document.getElementByClass(\"status\");`","D":"`const el = document.getElement(\"p#status\");`"},"answer":"A","why":"`getElementById` takes the bare id value, with no `#` prefix. `getElementByClass` and `getElement` are not real methods."},
  {"n":54,"section":7,"difficulty":"Applied","type":"Code","stem":[{"t":"text","v":"A quantity field's value is read from a form and compared:"},{"t":"code","lang":"javascript","v":"const entered = document.getElementById(\"qty\").value; // the user typed 5\nconsole.log(entered === 5);"},{"t":"text","v":"What is logged, and why?"}],"options":{"A":"`true`, because the user typed the number 5","B":"`true`, because `===` converts the types before comparing","C":"`false`, because `.value` gives the string `\"5\"`, and `===` compares type as well as value","D":"An error, because a string and a number cannot be compared"},"answer":"C","why":"Form field values are always strings, so `entered` is `\"5\"`. `===` compares type as well as value and does not convert, so a string never strictly equals a number."},
  {"n":55,"section":7,"difficulty":"Applied","type":"Scenario","stem":[{"t":"text","v":"A shopping cart badge is marked up as `<span id=\"cart-count\">0</span>`. After an item is added, the number must be updated to 1. Which line does this?"}],"options":{"A":"`document.getElementById(\"cart-count\") = 1;`","B":"`document.getElementById(\"cart-count\").value = 1;`","C":"`document.getElementById(\"cart-count\").id = 1;`","D":"`document.getElementById(\"cart-count\").textContent = 1;`"},"answer":"D","why":"`textContent` sets the text inside the element. `.value` applies to form controls rather than a `<span>`, assigning to the element itself is invalid, and `.id` would change its identifier."},
  {"n":56,"section":7,"difficulty":"Applied","type":"Scenario","stem":[{"t":"text","v":"An \"Add to cart\" button should run an existing `addToCart` function when it is clicked. Which line connects them correctly?"}],"options":{"A":"`addToCart(button);`","B":"`button.addEventListener(\"click\", addToCart);`","C":"`button.addEventListener(\"click\", addToCart());`","D":"`button.onClick = \"addToCart()\";`"},"answer":"B","why":"The handler must be passed as a reference. Adding `()` as in option C calls the function immediately and registers its return value instead."},
  {"n":57,"section":7,"difficulty":"Applied","type":"Workflow","stem":[{"t":"text","v":"A dashboard lets users switch between a light and a dark theme. The choice must still be in effect when the user closes the tab and returns the next day. Where should the preference be kept?"}],"options":{"A":"In `localStorage`, read on page load to reapply the saved theme","B":"In an ordinary JavaScript variable at the top of the script","C":"In a CSS class on the `<body>` element only","D":"In the URL's query string, which the browser remembers automatically"},"answer":"A","why":"`localStorage` persists across tab closes and browser restarts, so the theme can be reapplied on the next visit. An ordinary variable is lost on reload."},
  {"n":58,"section":7,"difficulty":"Applied","type":"Debugging","stem":[{"t":"text","v":"This script sits in the `<head>` of the page and throws `Cannot set properties of null`:"},{"t":"code","lang":"javascript","v":"document.getElementById(\"title\").textContent = \"Welcome\";"},{"t":"text","v":"The element `<h1 id=\"title\">` definitely exists in the `<body>`. What is happening?"}],"options":{"A":"`textContent` cannot be used on an `<h1>` element","B":"The id must be written as `\"#title\"` inside `getElementById`","C":"The script runs before the `<h1>` has been parsed, so `getElementById` returns `null`; move the script to the end of `<body>`, or add `defer`","D":"Only one element on a page may have an `id`, and another element already uses it"},"answer":"C","why":"A script in `<head>` executes before the body is parsed, so the element does not exist yet and `getElementById` returns `null`. Moving the script or adding `defer` delays it until the DOM is ready."},
  {"n":59,"section":7,"difficulty":"Problem-Solving","type":"Debugging","stem":[{"t":"text","v":"A contact form is validated in JavaScript, but the moment the user presses **Send** the page reloads and the error message disappears instantly:"},{"t":"code","lang":"javascript","v":"form.addEventListener(\"submit\", function (event) {\n  if (emailInput.value === \"\") {\n    showError(\"Email is required\");\n  }\n});"},{"t":"text","v":"What is missing?"}],"options":{"A":"The listener should be on `\"click\"` rather than `\"submit\"`","B":"`showError` must be declared with `const` instead of `function`","C":"The form needs `method=\"post\"` added to it","D":"`event.preventDefault()`, to stop the browser's default form submission while the validation runs"},"answer":"D","why":"Without `preventDefault()` the browser performs its default submit and reloads the page, discarding the message. The handler is on the right event."},
  {"n":60,"section":7,"difficulty":"Problem-Solving","type":"Debugging","stem":[{"t":"text","v":"A quantity stepper should add 1 to the current value, but `5` becomes `51` instead of `6`:"},{"t":"code","lang":"javascript","v":"const qty = document.getElementById(\"qty\").value;\nconst newQty = qty + 1;"},{"t":"text","v":"What is wrong, and how do you fix it?"}],"options":{"A":"`+` cannot be used on variables declared with `const`; use `let`","B":"`.value` returns a string, so `+` joins the text instead of adding; convert it first, for example `Number(qty) + 1`","C":"The input's `id` must be numeric for arithmetic to work","D":"`newQty` must be declared before `qty` for the addition to run"},"answer":"B","why":"`.value` is a string, so `\"5\" + 1` concatenates to `\"51\"`. Converting with `Number()` or `parseInt()` makes `+` perform arithmetic."}
];
